Repository Aju100/Django-Backend-mentorship, pull requests merged in 2021-06, with the labels that each got.

#53 feat:add contributors.rst
  config/settings/base.py
  config/urls.py
  docs/contributors.rst
  docs/index.rst
Labels: good first issue, review-progress

#59 feat: pr and issues template added
  .github/issue_template.md
  .github/pull_request_template.md
  README.rst
  docs/CONTRIBUTING.rst
  docs/index.rst
Labels: enhancement

#58 feat:contribution-guidelines-added
  README.rst
  docs/CONTRIBUTING.rst
  docs/index.rst
Labels: good first issue

#60 feat:added jazzmin
  config/settings/base.py
Labels: enhancement, review-progress

#61 chore: local ip env add
  .envs/.local/.django
  config/settings/local.py
Labels: good first issue
